<?php
/**
 * Catálogo de categorías de servicio. Fuente única de verdad para
 * categoria.html (listado) y producto.php (detalle por categoría).
 */
function catalogoCategorias(): array
{
    return [
        'plomeria' => [
            'nombre' => 'Plomería',
            'titulo' => 'Reparación y mantenimiento de instalaciones',
            'descripcion' => 'Soluciones de plomería para hogares, empresas y locales, con atención urgente y técnicos verificados.',
            'imagen' => 'assets/corporativas/corp-06-plomeria.webp',
            'galeria' => ['assets/corporativas/corp-06-plomeria.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '8.500',
            'trabajos' => '2.300',
            'rating' => '4.8',
            'respuesta' => '30 minutos',
            'incluye' => ['Diagnóstico previo', 'Reparación de fugas, cañerías y accesorios', 'Mantenimiento preventivo', 'Instalación de artefactos y conexiones'],
            'cuando' => ['Fugas o filtraciones', 'Reemplazo de cañerías', 'Ubicación de artefactos', 'Urgencias de vivienda o local'],
        ],
        'electricidad' => [
            'nombre' => 'Electricidad',
            'titulo' => 'Instalaciones, tableros y mantenimiento eléctrico',
            'descripcion' => 'Trabajos eléctricos residenciales, comerciales e industriales, con seguridad certificada y respuesta rápida.',
            'imagen' => 'assets/corporativas/corp-07-electricista.webp',
            'galeria' => ['assets/corporativas/corp-07-electricista.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '9.200',
            'trabajos' => '1.900',
            'rating' => '4.9',
            'respuesta' => '30 minutos',
            'incluye' => ['Diagnóstico de instalación', 'Recambio y actualización de tableros', 'Iluminación y tomacorrientes', 'Certificación de seguridad eléctrica'],
            'cuando' => ['Cortes de luz frecuentes', 'Tablero viejo o sin protección', 'Instalación de nuevos ambientes', 'Urgencias eléctricas'],
        ],
        'gas' => [
            'nombre' => 'Gas',
            'titulo' => 'Instalación, seguridad y mantenimiento de gas',
            'descripcion' => 'Instalaciones y revisiones de gas realizadas por matriculados, con foco en seguridad y cumplimiento normativo.',
            'imagen' => 'assets/corporativas/corp-17-planta-industrial.webp',
            'galeria' => ['assets/corporativas/corp-17-planta-industrial.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '10.000',
            'trabajos' => '1.440',
            'rating' => '4.7',
            'respuesta' => '1 hora',
            'incluye' => ['Revisión de instalación y conexiones', 'Detección de pérdidas', 'Instalación de artefactos a gas', 'Certificado de instalación'],
            'cuando' => ['Olor a gas o sospecha de pérdida', 'Instalación de nuevos artefactos', 'Habilitaciones y certificaciones', 'Mantenimiento preventivo anual'],
        ],
        'cerrajeria' => [
            'nombre' => 'Cerrajería',
            'titulo' => 'Aperturas, cerraduras y seguridad del hogar',
            'descripcion' => 'Apertura de puertas, cambio de cerraduras e instalaciones de seguridad, con atención de urgencia las 24 horas.',
            'imagen' => 'assets/corporativas/corp-16-oficina-noche.webp',
            'galeria' => ['assets/corporativas/corp-16-oficina-noche.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '7.500',
            'trabajos' => '1.120',
            'rating' => '4.8',
            'respuesta' => '20 minutos',
            'incluye' => ['Apertura de puertas sin daño', 'Cambio y duplicado de cerraduras', 'Instalación de cerraduras de seguridad', 'Asesoría en seguridad del hogar'],
            'cuando' => ['Quedaste afuera de tu casa o auto', 'Llave perdida o rota', 'Mudanza o cambio de inquilino', 'Refuerzo de seguridad'],
        ],
        'aire' => [
            'nombre' => 'Aire acondicionado',
            'titulo' => 'Instalación, limpieza y diagnóstico técnico',
            'descripcion' => 'Instalación y mantenimiento de equipos de climatización para que rindan todo el año, en casa o en el trabajo.',
            'imagen' => 'assets/corporativas/corp-08-aire.webp',
            'galeria' => ['assets/corporativas/corp-08-aire.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '11.300',
            'trabajos' => '1.280',
            'rating' => '4.8',
            'respuesta' => '1 hora',
            'incluye' => ['Instalación de equipos split e inverter', 'Limpieza de filtros y carga de gas', 'Diagnóstico de fallas', 'Mantenimiento preventivo estacional'],
            'cuando' => ['El equipo no enfría o no calefacciona', 'Instalación de un equipo nuevo', 'Ruidos o pérdidas de agua', 'Mantenimiento antes del verano'],
        ],
        'pintura' => [
            'nombre' => 'Pintura',
            'titulo' => 'Acabados, reformas de interior y exterior',
            'descripcion' => 'Pintura y terminaciones para renovar ambientes, con materiales de calidad y trabajo prolijo de principio a fin.',
            'imagen' => 'assets/corporativas/corp-18-pintura.webp',
            'galeria' => ['assets/corporativas/corp-18-pintura.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '7.900',
            'trabajos' => '980',
            'rating' => '4.9',
            'respuesta' => '2 horas',
            'incluye' => ['Preparación de superficies', 'Pintura de interior y exterior', 'Terminaciones e impermeabilización', 'Asesoría de color y materiales'],
            'cuando' => ['Renovar un ambiente o fachada', 'Humedad o descascarado', 'Pintura post-obra', 'Mantenimiento periódico'],
        ],
        'carpinteria' => [
            'nombre' => 'Carpintería',
            'titulo' => 'Reparaciones y trabajos de madera a medida',
            'descripcion' => 'Muebles, aberturas y reparaciones en madera, fabricadas o ajustadas a medida por carpinteros con oficio.',
            'imagen' => 'assets/corporativas/corp-03-taller.webp',
            'galeria' => ['assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-16-oficina-noche.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '8.100',
            'trabajos' => '760',
            'rating' => '4.6',
            'respuesta' => '2 horas',
            'incluye' => ['Fabricación de muebles a medida', 'Reparación de puertas y aberturas', 'Ajuste de bisagras y herrajes', 'Restauración de piezas de madera'],
            'cuando' => ['Puertas o ventanas que no cierran bien', 'Muebles rotos o a medida', 'Reformas de interior', 'Mantenimiento de aberturas'],
        ],
        'jardineria' => [
            'nombre' => 'Jardinería',
            'titulo' => 'Mantenimiento y diseño de espacios verdes',
            'descripcion' => 'Cuidado integral de jardines y espacios exteriores, desde el mantenimiento periódico hasta el diseño de nuevos espacios.',
            'imagen' => 'assets/corporativas/corp-13-topografia.webp',
            'galeria' => ['assets/corporativas/corp-13-topografia.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '7.000',
            'trabajos' => '640',
            'rating' => '4.8',
            'respuesta' => '2 horas',
            'incluye' => ['Corte de césped y poda', 'Diseño y armado de espacios verdes', 'Riego y fertilización', 'Limpieza de terrenos'],
            'cuando' => ['Jardín descuidado o crecido', 'Poda de árboles y arbustos', 'Preparación para el verano', 'Mantenimiento mensual'],
        ],
        'limpieza' => [
            'nombre' => 'Limpieza',
            'titulo' => 'Limpieza profunda para hogares y oficinas',
            'descripcion' => 'Servicios de limpieza puntual o periódica, con personal de confianza y productos adecuados para cada espacio.',
            'imagen' => 'assets/corporativas/corp-02-recepcion.webp',
            'galeria' => ['assets/corporativas/corp-02-recepcion.webp', 'assets/corporativas/corp-01-equipo-oficina.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-16-oficina-noche.webp'],
            'precio' => '6.500',
            'trabajos' => '1.560',
            'rating' => '4.8',
            'respuesta' => '1 hora',
            'incluye' => ['Limpieza general de ambientes', 'Limpieza profunda post-obra', 'Limpieza de oficinas y locales', 'Desinfección de superficies'],
            'cuando' => ['Mudanza o entrega de propiedad', 'Después de una obra o reforma', 'Limpieza periódica del hogar', 'Antes de un evento'],
        ],
        'mudanzas' => [
            'nombre' => 'Mudanzas',
            'titulo' => 'Mudanzas y fletes con cuidado en cada paso',
            'descripcion' => 'Mudanzas de hogares y oficinas con personal capacitado, vehículos propios y seguimiento del traslado.',
            'imagen' => 'assets/corporativas/corp-11-deposito-flota.webp',
            'galeria' => ['assets/corporativas/corp-11-deposito-flota.webp', 'assets/corporativas/corp-01-equipo-oficina.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-03-taller.webp'],
            'precio' => '15.000',
            'trabajos' => '420',
            'rating' => '4.7',
            'respuesta' => '24 horas',
            'incluye' => ['Embalaje de muebles y objetos frágiles', 'Carga, traslado y descarga', 'Mudanzas de hogares y oficinas', 'Seguimiento del traslado'],
            'cuando' => ['Cambio de vivienda u oficina', 'Traslado de pocos muebles (flete)', 'Mudanzas de larga distancia', 'Guardado temporal de muebles'],
        ],
        'tecnicos' => [
            'nombre' => 'Técnicos',
            'titulo' => 'Service técnico para equipos y electrodomésticos',
            'descripcion' => 'Reparación y mantenimiento de electrodomésticos y equipos técnicos, con diagnóstico claro antes de cada trabajo.',
            'imagen' => 'assets/corporativas/corp-05-cliente-tecnico.webp',
            'galeria' => ['assets/corporativas/corp-05-cliente-tecnico.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp'],
            'precio' => '9.500',
            'trabajos' => '890',
            'rating' => '4.8',
            'respuesta' => '1 hora',
            'incluye' => ['Diagnóstico de fallas', 'Reparación de electrodomésticos', 'Mantenimiento preventivo', 'Repuestos originales o compatibles'],
            'cuando' => ['El equipo no enciende o falla', 'Mantenimiento periódico', 'Instalación de equipos nuevos', 'Segunda opinión antes de comprar otro'],
        ],
        'otros' => [
            'nombre' => 'Otros servicios',
            'titulo' => 'Ese trabajo puntual que no encontrás en otro lado',
            'descripcion' => 'Para tareas que no entran en una categoría específica: contanos qué necesitás y te conectamos con el profesional adecuado.',
            'imagen' => 'assets/corporativas/corp-15-foto-equipo.webp',
            'galeria' => ['assets/corporativas/corp-15-foto-equipo.webp', 'assets/corporativas/corp-01-equipo-oficina.webp', 'assets/corporativas/corp-03-taller.webp', 'assets/corporativas/corp-16-oficina-noche.webp'],
            'precio' => '7.000',
            'trabajos' => '310',
            'rating' => '4.7',
            'respuesta' => '2 horas',
            'incluye' => ['Relevamiento de la tarea', 'Presupuesto a medida', 'Profesional acorde a la necesidad', 'Seguimiento hasta el cierre'],
            'cuando' => ['La tarea no encaja en otra categoría', 'Necesitás varias especialidades', 'Trabajos combinados o poco frecuentes', 'No sabés a quién llamar'],
        ],
    ];
}
